apiVersion: batch/v1
kind: CronJob
metadata:
  name: cache-cleanup
  namespace: arc-runners
spec:
  schedule: "* * * * *" # Run daily at midnight >> 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cache-cleanup
              image: busybox
              command: [
                  "sh",
                  "-c",
                  "echo 'Starting cache cleanup'; \
                  find /mnt/docker-cache -type f -mmin +60 -print -delete; \
                  echo 'Cache cleanup completed'",
                ] #Delete files older than 7 days >>  -mtime +7   older than 60m >> -mmin +60
              volumeMounts:
                - name: docker-build-cache
                  mountPath: /mnt/docker-cache
          restartPolicy: OnFailure
          volumes:
            - name: docker-build-cache
              persistentVolumeClaim:
                claimName: gh-runner-storage-pvc
