apiVersion: v1
kind: PersistentVolume
metadata:
  name: gh-runner-storage-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gh-runner-storage-class
  local:
    path: /mnt/docker-cache # Or any local path on your node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arc # Replace with your node's name or remove if not needed
